/**
 * 
 */
package discogs.style;

/**
 * @author tschepacz
 *
 */
public enum ElectronicStyle implements Style {

	ABSTRACT("Abstract"),
	ACID("Acid"),
	ACID_HOUSE("Acid House"),
	ACID_JAZZ("Acid Jazz"),
	AMBIENT("Ambient"),
	BALLROOM("Ballroom"),
	BALTIMORE_CLUB("Baltimore Club"),
	BASSLINE("Bassline"),
	BEATDOWN("Beatdown"),
	BERLIN_SCHOOL("Berlin-School"),
	BIG_BEAT("Big Beat"),
	BREAKBEAT("Breakbeat"),
	BREAKCORE("Breakcore"),
	BREAKS("Breaks"),
	BROKEN_BEAT("Broken Beat"),
	CHILLWAVE("Chillwave"),
	CHIPTUNE("Chiptune"),
	DANCE_POP("Dance-pop"),
	DARK_AMBIENT("Dark Ambient"),
	DARKWAVE("Darkwave"),
	DEEP_HOUSE("Deep House"),
	DEEP_TECHNO("Deep Techno"),
	DISCO("Disco"),
	DISCO_POLO("Disco Polo"),
	DONK("Donk"),
	DOOMCORE("Doomcore"),
	DOWNTEMPO("Downtempo"),
	DRONE("Drone"),
	DRUM_N_BASS("Drum n Bass"),
	DUB("Dub"),
	DUB_TECHNO("Dub Techno"),
	DUBSTEP("Dubstep"),
	DUNGEON_SYNTH("Dungeon Synth"),
	EBM("EBM"),
	ELECTRO("Electro"),
	ELECTRO_HOUSE("Electro House"),
	ELECTROCLASH("Electroclash"),
	EURO_HOUSE("Euro House"),
	EURO_DISCO("Euro-Disco"),
	EUROBEAT("Eurobeat"),
	EURODANCE("Eurodance"),
	EXPERIMENTAL("Experimental"),
	FREESTYLE("Freestyle"),
	FUNKOT("Funkot"),
	FUTURE_JAZZ("Future Jazz"),
	GABBER("Gabber"),
	GARAGE_HOUSE("Garage House"),
	GHETTO("Ghetto"),
	GHETTO_HOUSE("Ghetto House"),
	GHETTOTECH("Ghettotech"),
	GLITCH("Glitch"),
	GOA_TRANCE("Goa Trance"),
	GRIME("Grime"),
	HANDS_UP("Hands Up"),
	HAPPY_HARDCORE("Happy Hardcore"),
	HARD_BEAT("Hard Beat"),
	HARD_HOUSE("Hard House"),
	HARD_TECHNO("Hard Techno"),
	HARD_TRANCE("Hard Trance"),
	HARDCORE("Hardcore"),
	HARDSTYLE("Hardstyle"),
	HARSH_NOISE_WALL("Harsh Noise Wall"),
	HI_NRG("Hi NRG"),
	HIP_HOP("Hip Hop"),
	HIP_HOUSE("Hip-House"),
	HOUSE("House"),
	IDM("IDM"),
	ILLBIENT("Illbient"),
	INDUSTRIAL("Industrial"),
	ITALO_HOUSE("Italo House"),
	ITALO_DISCO("Italo-Disco"),
	ITALODANCE("Italodance"),
	J_CORE("J-Core"),
	JAZZDANCE("Jazzdance"),
	JUKE("Juke"),
	JUMPSTYLE("Jumpstyle"),
	JUNGLE("Jungle"),
	LATIN("Latin"),
	LEFTFIELD("Leftfield"),
	MAKINA("Makina"),
	MINIMAL("Minimal"),
	MINIMAL_TECHNO("Minimal Techno"),
	MODERN_CLASSICAL("Modern Classical"),
	MUSIQUE_CONCRÈTE("Musique Concrète"),
	NEO_TRANCE("Neo Trance"),
	NEOFOLK("Neofolk"),
	NEW_AGE("New Age"),
	NEW_BEAT("New Beat"),
	NEW_WAVE("New Wave"),
	NOISE("Noise"),
	NU_DISCO("Nu-Disco"),
	POWER_ELECTRONICS("Power Electronics"),
	PROGRESSIVE_BREAKS("Progressive Breaks"),
	PROGRESSIVE_HOUSE("Progressive House"),
	PROGRESSIVE_TRANCE("Progressive Trance"),
	PSY_TRANCE("Psy-Trance"),
	RHYTHMIC_NOISE("Rhythmic Noise"),
	SCHRANZ("Schranz"),
	SKWEEE("Skweee"),
	SOUND_COLLAGE("Sound Collage"),
	SPEED_GARAGE("Speed Garage"),
	SPEEDCORE("Speedcore"),
	SYNTH_POP("Synth-pop"),
	SYNTHWAVE("Synthwave"),
	TECH_HOUSE("Tech House"),
	TECH_TRANCE("Tech Trance"),
	TECHNO("Techno"),
	TRANCE("Trance"),
	TRIBAL("Tribal"),
	TRIBAL_HOUSE("Tribal House"),
	TRIP_HOP("Trip Hop"),
	TROPICAL_HOUSE("Tropical House"),
	UK_GARAGE("UK Garage"),
	VAPORWAVE("Vaporwave"),
	WITCH_HOUSE("Witch House");
	
	private String style;
	
	ElectronicStyle(String style){
		this.style = style;
	}
}
